import Foundation

/// Recoverability guidance, never proof that a folder is unused or safe to delete.
public enum CleanupGuidance {
    public static func chromeCacheNote(path: String, home: String = FileManager.default.homeDirectoryForCurrentUser.path) -> String? {
        let cache = URL(fileURLWithPath: home).appendingPathComponent("Library/Caches/Google/Chrome").standardizedFileURL.path
        let normalized = URL(fileURLWithPath: path).standardizedFileURL.path
        guard normalized == cache || normalized.hasPrefix(cache + "/") else { return nil }
        return "This is Chrome cache, separate from your browser profile. Clearing it can remove offline site data and make pages reload; cookies and sign-ins usually remain. Quit Chrome before reviewing cleanup."
    }

    public static func label(for category: DeveloperCategory?) -> String {
        switch category {
        case .packageCaches, .nodeModules, .installedModules: "Usually regenerable"
        case .installers: "Usually re-downloadable"
        case .claudeSessions, .codexSessions: "Not regenerable · archive first"
        default: "Regeneration unconfirmed"
        }
    }

    public static func explanation(for category: DeveloperCategory?) -> String {
        switch category {
        case .packageCaches:
            "Usually downloadable again. Offline or unavailable versions and local changes may be lost."
        case .nodeModules, .installedModules:
            "Usually reinstallable from the project's dependency manifest. Check that required versions are available and no local changes need keeping."
        case .buildOutputs:
            "A build-folder name does not confirm that its contents can be rebuilt. Check the project and build inputs before cleanup."
        case .claudeSessions, .codexSessions:
            "Conversation history cannot be regenerated by reinstalling the tool. Preserve an archive before cleanup."
        case .installers:
            "An installer is not the installed app. If the app is installed and still distributed, the installer can usually be downloaded again — verify before cleanup."
        case .oldDownloads:
            "Age alone does not make a file safe to remove. Some downloads are the only copy of a file; review contents before cleanup."
        default:
            "May contain original work or persistent data. Regeneration has not been confirmed; review contents before cleanup."
        }
    }

    /// Batch suggestions deliberately exclude broad stores, local repositories,
    /// environments and name-only build matches. Existing preflight still applies.
    public static func isSuggestedCache(category: DeveloperCategory, path: String, home: String = FileManager.default.homeDirectoryForCurrentUser.path) -> Bool {
        guard category == .packageCaches else { return false }
        let url = URL(fileURLWithPath: path)
        let parent = url.deletingLastPathComponent().standardizedFileURL.path
        let base = URL(fileURLWithPath: home).standardizedFileURL
        let roots = [base.appendingPathComponent("Library/Caches").path, base.appendingPathComponent(".cache").path]
        let aliases = roots.map { "/System/Volumes/Data" + $0 }
        let tool = url.lastPathComponent.lowercased()
        return (roots + aliases).contains(parent)
            && ["npm", "pnpm", "yarn", "pip", "uv", "go-build", "cocoapods", "composer"].contains(tool)
    }
}
